"""add index gin

Revision ID: 42f9ad210902
Revises: 8e8b4af4f635
Create Date: 2022-09-14 20:29:56.797949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f9ad210902'
down_revision = '8e8b4af4f635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_examples_tsv', 'post', ['body_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_examples_tsv', table_name='post', postgresql_using='gin')
    # ### end Alembic commands ###
