"""add body_vector

Revision ID: 4a28ee547b4e
Revises: 17bba0ef45f3
Create Date: 2022-09-14 18:23:12.678530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a28ee547b4e'
down_revision = '17bba0ef45f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('lang', sa.String(length=30), nullable=True))
    op.add_column('post', sa.Column('body_vector', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_vector')
    op.drop_column('post', 'lang')
    # ### end Alembic commands ###
